title: ConstWerk
description: This is my personal blog
impressum: Impressum

plugins:

theme: minima

minima:

show_excerpts: false


minima:
  skin: auto
  date_format: "%Y-%m-%d"
  social_links:  
   - { platform: github,         user_url: "https://github.com/cuhde" }
   - { platform: google_scholar, user_url: "https://scholar.google.de/citations?user=8JTCNCIAAAAJ&hl=en" }
   - { platform: linkedin,       user_url: "https://de.linkedin.com/in/constantin-uhde-9355b8137" }

author: Constantin Uhde
e_mail: info@constwerk.com

header_pages:
  - _pages/frontpage.md
  - _pages/catchup.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - README.md


