title: ConstWerk

description: This is my personal blog
impressum: Impressum

author: 
  name: Constantin Uhde
  email: info@constwerk.com

plugins:
  - jekyll-remote-theme

#theme: minima
remote_theme: jekyll/minima

include:
  - _pages

exclude: 
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md

minima:
  skin: solarized
  date_format: "%Y-%m-%d"
  social_links:  
    - title: GitHub
      icon: github
      url: "https://github.com/cuhde"
    - title: LinkedIn
      icon: linkedin
      url: "https://de.linkedin.com/in/constantin-uhde-9355b8137"
    - title: Google Scholar
      icon: google-scholar
      url: "https://scholar.google.de/citations?user=8JTCNCIAAAAJ&hl=en"

  show_excerpts: true

  nav_pages:
    - _pages/frontpage.md
    - _pages/catchup.md
    - _pages/archive.md




